name = "propmanage-ai-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "8253b30c0106148cfe2add2a62792196"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "propmanage-db"
database_id = "ff6063f0-70f7-4149-ae7d-1c71d5f1fc2f"

[observability]
enabled = true
